lang: en-US
title: "Hanyuu's Command"
url: "https://ayeven.github.io/hanyuu/"
repository: "ayeven/hanyuu"
author: 
  name: "Ayeven#9725"
  picture:
github_username: "Ayeven"
logo: /assets/icons/10000000000022934.bmp
remote_theme: "ayeven/jekyll-theme-basically-basic@1.4.5"
